### ISSUE TITLE
Issues with the display

### ISSUE THREAD

**Issue by ktomi96** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#10]
Hello 

I have a Two Trees Bluer V2 printer.
Mks robin nano v1.2
The pre-complied version worked fine, but i installed 3d touch to my printer to it. So i tried to compli it in vscode with platformio and with automarlin too. I copied the .bin and assets folder to the sd- card.
The screen wouldnt work properly, it had glitches and overlaying icons so i couldnt use it.

Any help would be appriecated, also i included the configs too.

[config.zip](https://github.com/RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI/files/6843470/config.zip)

**Comment by RolfZuckowskiUltras** [comment]
Hey,
did you fully refer to the firmware-loading-process? You do have to load the LVGL-gui-assets when loading a custom firmware.

```

  -  Enter the .pio\build\mks_robin_nano35 directory, **copy the assets folder and Robin_nano35.bin to the sd card**
  -  Insert SD card to the motherboard, and you can see the update interface after power on.


```
