### ISSUE TITLE
Lcd is inverted

### ISSUE THREAD

**Issue by Foaxulapa** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#14]
Good night
I have a Sapphire Plus
Motherboard (STM32F103VET6) and when I updated it with (Sapphire_Plus_Dual_Z_Hemera) the Lcd is inverted, I would like your help! Thanks

![20211012_232221 1](https://user-images.githubusercontent.com/92413936/137057789-9557c183-42fa-4579-b5c0-c8d65447090f.jpg)

**Comment by RolfZuckowskiUltras** [comment]
Hey,
not quite shure if this is a new revision or "factory variation" of TwoTrees, where the LCD is turned.
All Revisions I've seen hat the Sapphire logo as sticker. Your one is printed, which may could refer to a newer revision with different Mainboard.

The needed infomation of the mainboard is rather the model-name, than the model of the controller. Shouls be Robin Nano 1.X or 2.0 in your case.

In case you've got the 2.0, please refer the desription of this repo. If it's still upsidedown, you can turn the display orientation in configuration.h (see below).

```
/**
 * TFT Rotation. Set to one of the following values:
 *
 *   TFT_ROTATE_90,  TFT_ROTATE_90_MIRROR_X,  TFT_ROTATE_90_MIRROR_Y,
 *   TFT_ROTATE_180, TFT_ROTATE_180_MIRROR_X, TFT_ROTATE_180_MIRROR_Y,
 *   TFT_ROTATE_270, TFT_ROTATE_270_MIRROR_X, TFT_ROTATE_270_MIRROR_Y,
 *   TFT_MIRROR_X, TFT_MIRROR_Y, TFT_NO_ROTATION
 */
//#define TFT_ROTATION TFT_NO_ROTATION
```
