### ISSUE TITLE
README.MD INCORRECT

### ISSUE THREAD

**Issue by youarewithoutadoubtfullofshit** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#15]
![image](https://user-images.githubusercontent.com/92617611/137573621-37889048-7b09-4421-83d9-d8d1f1c4fcf1.png)

Please see README.md......

the value you suggest people change doesn't exist

**Comment by RolfZuckowskiUltras** [comment]
Hey,
it seems like you're did open the wrong project. At least the configuration.h is not the version of this repo.
