### ISSUE TITLE
Issue with Preconfig for v1.3 board

### ISSUE THREAD

**Issue by Semparo-Taro** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#21]
Unsure if I'm doing something wrong, but I have the S-Plus with Dual Z with Belt Sync.  The board is v1.3.  When I try the precompiled file it starts the update but hangs on 100%
![photo_2022-01-07_23-08-12 (2)](https://user-images.githubusercontent.com/97327926/148632360-2fad15f0-c572-4594-ba2f-22ed068cbc90.jpg)
![photo_2022-01-07_23-08-12](https://user-images.githubusercontent.com/97327926/148632362-089b565b-e4a2-49a9-b108-24600c18d633.jpg)

**Comment by RolfZuckowskiUltras** [comment]
This might be cause by the board beeing a newer release than the actual precompiled files. So I maybe have to update the project with the files from marlin at some point at time, to make this work.

**Comment by RolfZuckowskiUltras** [comment]
@Semparo-Taro You may wanna try out my new Repo. It does contain the newest stable Marlin revision.
