### ISSUE TITLE
Filament Problem on Plus

### ISSUE THREAD

**Issue by luismurias2** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#5]
Hello sir 

Thx for your work. I downloaded your firmware to my Plus "Sapphire_Plus_Dual_Z.zip" but the filament when I try to print instead of going IN is going OUT

Hope you can solve this THX 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Filippo-est** [comment]
the fastest way is to reverse the polarity of the stepper motor

**Comment by RolfZuckowskiUltras** [comment]
Hey,
thanks Filippo-est! Thats the hardware-based fix for this Problem.

The Problem may be cause by the usage of a different stepper, than the original stepper set.

**The most clean method** is to compile your own firmware and just change the configuration of the E-Stepper direction.

If you're lazy, you may try to set the negate the e-steps value by serial terminal connection. But that one is not recommended..
