### ISSUE TITLE
Filamentsensor

### ISSUE THREAD

**Issue by HighControl** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#6]
Der Filamentsensor ist ohne Funktion und lässt sich auch nicht aktivieren.

**Comment by RolfZuckowskiUltras** [comment]
Die Funktion ist in der vorkompilierten Firmware nicht aktiviert, da dieser im Fabrikzustand nicht vormontiert ist. Zur Aktivierung erstellst du am besten deine eigene Fork und aktivierst diese Funktion in dieser.
